'import warnings' failed; traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/warnings.py", line 538, in <module>
    _processoptions(sys.warnoptions)
  File "/usr/lib/python3.8/warnings.py", line 208, in _processoptions
    _setoption(arg)
  File "/usr/lib/python3.8/warnings.py", line 224, in _setoption
    import re
  File "/usr/lib/python3.8/re.py", line 127, in <module>
    import functools
  File "/usr/lib/python3.8/functools.py", line 18, in <module>
    from collections import namedtuple
  File "/usr/lib/python3.8/collections/__init__.py", line 26, in <module>
    from itertools import repeat as _repeat, chain as _chain, starmap as _starmap
KeyboardInterrupt
